name: Build and Push to Docker Hub

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nwgate.ru:${{ github.ref_name }} .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nwgate.ru:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nwgate.ru:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nwgate.ru:latest
